[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
datdev = "uUoKq6s3qzAYfRuBuZaqUGzFUem8CjSe4yyYThSoo8y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/shradhesh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
