'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { 
  Code2, 
  Rocket, 
  DollarSign, 
  Users, 
  Zap,
  ChevronRight,
  CheckCircle,
  Terminal,
  GitBranch,
  Shield,
  TrendingUp,
  Layers,
  Award
} from '@/components/icons';

export default function DeveloperLandingPage() {
  const features = [
    {
      icon: <Code2 className="w-8 h-8" />,
      title: "Build DeFi Vaults",
      description: "Create sophisticated yield-generating vaults with our comprehensive SDK and tools.",
      color: "from-[#8B5CF6] to-[#6D28D9]"
    },
    {
      icon: <DollarSign className="w-8 h-8" />,
      title: "Earn Revenue Share",
      description: "Get 30% of all fees generated by your vaults. The more successful your vault, the more you earn.",
      color: "from-[#FACC15] to-[#F59E0B]"
    },
    {
      icon: <Shield className="w-8 h-8" />,
      title: "Secure Infrastructure",
      description: "Built on battle-tested smart contracts with comprehensive security audits.",
      color: "from-[#FF007A] to-[#CC0062]"
    },
    {
      icon: <GitBranch className="w-8 h-8" />,
      title: "Version Control",
      description: "Manage vault versions, rollbacks, and updates with built-in version control.",
      color: "from-[#00E0FF] to-[#0099CC]"
    },
    {
      icon: <Users className="w-8 h-8" />,
      title: "Developer Community",
      description: "Join a thriving community of DeFi developers building the future of finance.",
      color: "from-[#8B5CF6] to-[#FF007A]"
    },
    {
      icon: <TrendingUp className="w-8 h-8" />,
      title: "Analytics Dashboard",
      description: "Track vault performance, user engagement, and revenue in real-time.",
      color: "from-[#00E0FF] to-[#8B5CF6]"
    }
  ];

  const developmentSteps = [
    {
      step: "1",
      title: "Design Your Strategy",
      description: "Define your vault's investment strategy and risk parameters.",
      icon: <Layers className="w-6 h-6" />
    },
    {
      step: "2",
      title: "Build & Test",
      description: "Use our SDK to build and test your vault in a sandbox environment.",
      icon: <Code2 className="w-6 h-6" />
    },
    {
      step: "3",
      title: "Deploy & Launch",
      description: "Deploy your vault to mainnet and start attracting investors.",
      icon: <Rocket className="w-6 h-6" />
    },
    {
      step: "4",
      title: "Earn & Scale",
      description: "Monitor performance, earn revenue, and scale your vault ecosystem.",
      icon: <DollarSign className="w-6 h-6" />
    }
  ];

  const benefits = [
    "30% revenue share on all fees",
    "Comprehensive SDK and documentation",
    "Sandbox testing environment",
    "Smart contract templates",
    "Security audit support",
    "Marketing and promotion",
    "24/7 technical support",
    "Developer grants available"
  ];

  const techStack = [
    { name: "Solidity", color: "#363636" },
    { name: "TypeScript", color: "#3178C6" },
    { name: "React", color: "#61DAFB" },
    { name: "Web3.js", color: "#F16822" },
    { name: "Hardhat", color: "#FFF100" },
    { name: "IPFS", color: "#65C2CB" }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#0B0C14] via-[#1a0b2e] to-[#0B0C14]">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#0B0C14]/90 backdrop-blur-md border-b border-white/5">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="text-2xl font-bold bg-gradient-to-r from-[#8B5CF6] to-[#FF007A] bg-clip-text text-transparent">
            Learn2Launch
          </Link>
          <div className="flex items-center space-x-4">
            <Link 
              href="/" 
              className="text-gray-400 hover:text-white transition-colors"
            >
              Back to Home
            </Link>
            <Link
              href="/dashboard/developer"
              className="px-6 py-2 bg-gradient-to-r from-[#8B5CF6] to-[#FF007A] text-white rounded-full font-semibold hover:shadow-[0_0_20px_rgba(139,92,246,0.6)] transition-all duration-300"
            >
              Go to Dashboard
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-6 relative overflow-hidden">
        {/* Animated Background */}
        <div className="absolute inset-0 opacity-10">
          <div className="absolute inset-0" style={{
            backgroundImage: 'linear-gradient(#8B5CF6 1px, transparent 1px), linear-gradient(90deg, #8B5CF6 1px, transparent 1px)',
            backgroundSize: '50px 50px',
          }} />
        </div>

        {/* Flowing code lines */}
        <div className="absolute inset-0 overflow-hidden opacity-20">
          {[...Array(20)].map((_, i) => (
            <motion.div
              key={i}
              className="absolute text-[#8B5CF6]/50 font-mono text-xs whitespace-nowrap"
              style={{
                left: `${Math.random() * 100}%`,
                top: `${Math.random() * 100}%`,
              }}
              animate={{
                y: [-100, 800],
                opacity: [0, 1, 0],
              }}
              transition={{
                duration: 5 + Math.random() * 3,
                repeat: Infinity,
                delay: Math.random() * 3,
                ease: 'linear',
              }}
            >
              {['function deploy()', 'contract Vault', 'uint256 yield', 'mapping(address)', 'event Deposit'][Math.floor(Math.random() * 5)]}
            </motion.div>
          ))}
        </div>

        <div className="max-w-7xl mx-auto relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center space-y-6"
          >
            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ delay: 0.2, type: "spring" }}
              className="inline-block px-4 py-2 bg-[#8B5CF6]/10 border border-[#8B5CF6]/30 rounded-full text-[#8B5CF6] text-sm font-medium"
            >
              ⚡ For Builders
            </motion.div>

            <h1 className="text-5xl md:text-7xl font-bold bg-gradient-to-r from-[#8B5CF6] via-[#FF007A] to-[#FACC15] bg-clip-text text-transparent">
              Build. Deploy. Earn.
            </h1>

            <p className="text-xl md:text-2xl text-gray-400 max-w-3xl mx-auto leading-relaxed">
              Create sophisticated DeFi vaults and earn 30% revenue share. 
              Join the future of decentralized finance development.
            </p>

            <div className="flex flex-wrap justify-center gap-4 pt-6">
             <Link
                href="/builder"
                className="group px-8 py-4 bg-gradient-to-r from-[#8B5CF6] to-[#FF007A] text-white rounded-full font-semibold hover:shadow-[0_0_30px_rgba(139,92,246,0.6)] transition-all duration-300 flex items-center space-x-2"
              >
                <span>Start Building</span>
                <ChevronRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </Link>

              <Link
                href="/dashboard/developer"
                className="px-8 py-4 bg-[#8B5CF6]/10 border border-[#8B5CF6]/50 text-[#8B5CF6] rounded-full hover:bg-[#8B5CF6]/20 transition-all duration-300 flex items-center space-x-2"
              >
                <Terminal className="w-5 h-5" />
                <span>Developer Dashboard</span>
              </Link>
            </div>

            {/* Stats */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.6 }}
              className="grid grid-cols-2 md:grid-cols-4 gap-6 pt-12 max-w-4xl mx-auto"
            >
              {[
                { value: "$2.5M+", label: "TVL" },
                { value: "150+", label: "Active Vaults" },
                { value: "30%", label: "Revenue Share" },
                { value: "500+", label: "Developers" }
              ].map((stat, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, scale: 0.5 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.8 + index * 0.1 }}
                  className="p-4 bg-white/5 backdrop-blur-sm rounded-xl border border-white/10"
                >
                  <div className="text-3xl font-bold bg-gradient-to-r from-[#8B5CF6] to-[#FF007A] bg-clip-text text-transparent">{stat.value}</div>
                  <div className="text-sm text-gray-400">{stat.label}</div>
                </motion.div>
              ))}
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-6 relative">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
              Everything You Need to Build
            </h2>
            <p className="text-xl text-gray-400 max-w-2xl mx-auto">
              Powerful tools and infrastructure for building next-generation DeFi vaults
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                whileHover={{ y: -10 }}
                className="group p-6 bg-white/5 backdrop-blur-sm rounded-2xl border border-white/10 hover:border-[#8B5CF6]/50 transition-all duration-300"
              >
                <div className={`w-16 h-16 rounded-xl bg-gradient-to-br ${feature.color} flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300`}>
                  {feature.icon}
                </div>
                <h3 className="text-xl font-bold text-white mb-2">{feature.title}</h3>
                <p className="text-gray-400">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Development Steps Section */}
      <section className="py-20 px-6 relative">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
              From Idea to Production
            </h2>
            <p className="text-xl text-gray-400">
              A streamlined process to bring your vault to life
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {developmentSteps.map((item, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, x: -30 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.2 }}
                className="relative"
              >
                {/* Connector Line */}
                {index < developmentSteps.length - 1 && (
                  <div className="hidden lg:block absolute top-12 left-full w-full h-0.5 bg-gradient-to-r from-[#8B5CF6] to-transparent" />
                )}

                <div className="relative p-6 bg-gradient-to-br from-white/10 to-white/5 backdrop-blur-sm rounded-2xl border border-white/10 hover:border-[#8B5CF6]/50 transition-all duration-300">
                  {/* Step Number */}
                  <div className="absolute -top-4 -left-4 w-12 h-12 bg-gradient-to-br from-[#8B5CF6] to-[#FF007A] rounded-full flex items-center justify-center text-xl font-bold shadow-lg">
                    {item.step}
                  </div>

                  <div className="mt-4">
                    <div className="w-12 h-12 bg-[#8B5CF6]/20 rounded-lg flex items-center justify-center text-[#8B5CF6] mb-4">
                      {item.icon}
                    </div>
                    <h3 className="text-xl font-bold text-white mb-2">{item.title}</h3>
                    <p className="text-gray-400 text-sm">{item.description}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Tech Stack Section */}
      <section className="py-20 px-6 relative">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
              Modern Tech Stack
            </h2>
            <p className="text-xl text-gray-400">
              Built with industry-leading technologies
            </p>
          </motion.div>

          <div className="flex flex-wrap justify-center gap-6">
            {techStack.map((tech, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, scale: 0.5 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                whileHover={{ scale: 1.1 }}
                className="px-6 py-3 bg-white/5 backdrop-blur-sm rounded-full border border-white/10 hover:border-[#8B5CF6]/50 transition-all duration-300"
              >
                <span className="text-white font-medium">{tech.name}</span>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-20 px-6 relative">
        <div className="max-w-6xl mx-auto">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
                Why Developers Choose Us
              </h2>
              <p className="text-xl text-gray-400 mb-8">
                Join hundreds of developers building the future of DeFi
              </p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {benefits.map((benefit, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: index * 0.05 }}
                    className="flex items-center space-x-3"
                  >
                    <CheckCircle className="w-5 h-5 text-[#8B5CF6] flex-shrink-0" />
                    <span className="text-gray-300">{benefit}</span>
                  </motion.div>
                ))}
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="relative"
            >
              <div className="relative p-8 bg-gradient-to-br from-[#8B5CF6]/20 to-[#FF007A]/20 rounded-3xl border border-[#8B5CF6]/30 backdrop-blur-sm">
                {/* Terminal mockup */}
                <div className="bg-[#0B0C14] rounded-xl p-6 font-mono text-sm">
                  <div className="flex items-center space-x-2 mb-4">
                    <div className="w-3 h-3 rounded-full bg-red-500" />
                    <div className="w-3 h-3 rounded-full bg-yellow-500" />
                    <div className="w-3 h-3 rounded-full bg-green-500" />
                  </div>
                  
                  <div className="space-y-2">
                    <div className="text-[#8B5CF6]">$ npx create-vault my-defi-vault</div>
                    <div className="text-gray-400">Creating new vault...</div>
                    <div className="text-green-400">✓ Vault initialized</div>
                    <div className="text-green-400">✓ Smart contracts generated</div>
                    <div className="text-green-400">✓ Tests created</div>
                    <div className="text-[#FF007A]">&gt; <span className="text-white">Ready to deploy!</span></div>
                    <motion.div
                      animate={{ opacity: [0, 1, 0] }}
                      transition={{ duration: 1.5, repeat: Infinity }}
                      className="text-[#8B5CF6]"
                    >
                      ▊
                    </motion.div>
                  </div>
                </div>

                {/* Floating badges */}
                <motion.div
                  animate={{ y: [0, -20, 0] }}
                  transition={{ duration: 4, repeat: Infinity }}
                  className="absolute -top-6 -right-6 px-4 py-2 bg-gradient-to-r from-[#FACC15] to-[#F59E0B] rounded-full font-bold shadow-lg"
                >
                  30% Revenue
                </motion.div>

                <motion.div
                  animate={{ y: [0, 20, 0] }}
                  transition={{ duration: 3, repeat: Infinity, delay: 1 }}
                  className="absolute -bottom-4 -left-4 px-4 py-2 bg-gradient-to-r from-[#00E0FF] to-[#0099CC] rounded-full font-bold shadow-lg"
                >
                  Instant Deploy
                </motion.div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-6 relative">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="relative p-12 bg-gradient-to-br from-[#8B5CF6]/20 to-[#FF007A]/20 rounded-3xl border border-[#8B5CF6]/30 backdrop-blur-sm text-center overflow-hidden"
          >
            {/* Animated Background */}
            <div className="absolute inset-0 opacity-20">
              <motion.div
                animate={{
                  backgroundPosition: ['0% 0%', '100% 100%'],
                }}
                transition={{
                  duration: 10,
                  repeat: Infinity,
                  repeatType: 'reverse',
                }}
                className="w-full h-full"
                style={{
                  backgroundImage: 'radial-gradient(circle, #8B5CF6 1px, transparent 1px)',
                  backgroundSize: '50px 50px',
                }}
              />
            </div>

            <div className="relative z-10">
              <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
                Ready to Build the Future?
              </h2>
              <p className="text-xl text-gray-300 mb-8">
                Start creating your DeFi vault today and earn revenue from day one
              </p>

              <div className="flex flex-col items-center gap-4">
                <Link
                  href="/builder"
                  className="inline-flex items-center space-x-2 px-10 py-5 bg-gradient-to-r from-[#8B5CF6] to-[#FF007A] text-white rounded-full font-bold text-lg hover:shadow-[0_0_40px_rgba(139,92,246,0.8)] transition-all duration-300 group"
                >
                  <span>Join Builder Marketplace</span>
                  <ChevronRight className="w-6 h-6 group-hover:translate-x-2 transition-transform" />
                </Link>

                <Link
                  href="/dashboard/developer"
                  className="inline-flex items-center space-x-2 px-10 py-5 bg-white/5 border border-[#8B5CF6]/50 text-white rounded-full font-bold text-lg hover:bg-white/10 transition-all duration-300 group"
                >
                  <span>Access Developer Dashboard</span>
                  <ChevronRight className="w-6 h-6 group-hover:translate-x-2 transition-transform" />
                </Link>
              </div>

              <p className="text-sm text-gray-400 mt-6">
                Free to start • Deploy in minutes • Earn 30% revenue share
              </p>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 px-6 border-t border-white/10">
        <div className="max-w-7xl mx-auto text-center text-gray-400">
          <p>&copy; 2025 Learn2Launch. Building the future of decentralized finance.</p>
        </div>
      </footer>
    </div>
  );
}
